# Generated by Django 2.2.5 on 2019-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'blogimage',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='blogtype',
            table='blogtype',
        ),
    ]
